name: Test PDF Data Extract to Excel

# on - speficifies the events that run/trigger the workflow
on:
  push:
    branches:
      - main

# jobs: difines the tasks to be defined in the workflow
jobs:
  build:
    # Specifies the type of machine the jobs will run
    runs-on: Windows-2022
    # Defines individual tasks within a job
    steps:
      # name CAN HAVE ANY NAME
      - name: Checkout code
        # uses - is used to run any COMMAND or EXTERNAL TOOL from the local IDE
        # AND is the first action which downloads the code from the repo to the GitHub virtual machine (runner).
        # v4 - is the last update of the GitHub has available the action checkout 
        uses: actions/checkout@v4

      # Makes the GitHub virtual machine (runner) downloads and set up the python version
      # to the GitHub workflow environment.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Python version of the project
          python-version: '3.12'
      

      # run MUST HAVE machine commands (if ubuntu or windows)
      # Install dependencies (same as when installing external libraries to the local IDE)
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Download PDF file
        # run: | - used when multiple steps are needed:
        # run: |
        #  command_1
        #  command_2
        # By default (only 1 command) should be: run: command_1
        # If condition check if the folder data exists, if not create the folder "data"
        run: |
          if (!(Test-Path -Path "data")) {New-Item -ItemType Directory -Path "data"}
          curl -L -o data/part_number_chart.pdf https://github.com/hydra-code-repository/pdf_data_extract_to_excel/raw/main/data/part_number_chart.pdf

      # step to list all files the data folder contains and make sure the .pdf file is present
      - name: List files from folder data
        run: dir data

      - name: Run notebook
        run: jupyter nbconvert --to notebook --execute notebook/pdf_extract.ipynb --output notebook/pdf_extract.ipynb      